[package]
name = "rustic-typster"
version = "0.1.0"
authors = ["blaisdellma <blaisdellma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
async-std = "1.7.0"
futures = "0.3.8"
futures-timer = "3.0.2"
crossterm = {version = "0.18.2", features = ["event-stream"]}
